executables like `sudo` in NixOS come from `/run/wrappers/bin`
juspay/nixos-unified-template pull request #19
Opened 2024-03-04 14:07 UTC by shivaraj-bh

If not present, sudo command will fail to run in NixOS if someone is sharing this configuration across NixOS, macOS and other linux distro.

This is on my NixOS:
```sh
shivaraj in 🌐 nixos in nix-dev-home on  export-wrappers-path
❯ which sudo
/run/wrappers/bin/sudo
```

2024-03-04 14:09 UTC, shivaraj-bh commented
If not present, it might be symlinked elsewhere, like:
```sh
❯ which sudo
/run/current-system/sw/bin/sudo
```

Leading to:
```sh
❯ sudo
sudo: /run/current-system/sw/bin/sudo must be owned by uid 0 and have the setuid bit set
```

2024-03-04 16:23 UTC, srid reviewed
> If not present, sudo command will fail to run in NixOS if someone is sharing this configuration across NixOS, macOS and other linux distro.

Why is this happening? I never had to face this myself in https://github.com/srid/nixos-config despite sharing like that (with the exception of other Linux distro which I do not use).

2024-03-04 16:36 UTC, shivaraj-bh commented
This might be related: https://discourse.nixos.org/t/sudo-run-current-system-sw-bin-sudo-must-be-owned-by-uid-0-and-have-the-setuid-bit-set-and-cannot-chdir-var-cron-bailing-out-var-cron-permission-denied/20463

2024-03-13 13:25 UTC, srid requested changes
Okay, let's do this - but add this PATH only when we are on NixOS.

```sh
$ nix run nixpkgs#lsb-release -- -i -s
"NixOS"
```

(This command is unavailable on Darwin though)

2024-03-17 11:44 UTC, srid commented
Alternatively, we can just test for `stdenv.isLinux`.

2024-10-04 15:57 UTC, srid commented
Let's re-evaluate this as part of #86

2024-10-04 15:57 UTC, closed without merging